# Site settings
title: Roberto Ramos's CV 
description: Curriculum de Roberto Ramos
favicon: /assets/img/avatar.JPG
baseurl: 
url: 
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Roberto Ramos
  title: Desenvolvedor de Software
  address: Pernambuco, Brasil
  email: robertolopesramos@gmail.com
  link: http://robertoramos.com.br
  weibo:
  github: Gambya
  linkedin: robertolopesramos
  twitter: robertolramos
  gavatar: gambya
  stackoverflow: 5086423
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: Kurier Brasil
      location: Recife-PE, Brasil
      title: Developer
      started: 2014
      duration: (2014 - Present)
      description: Desenvolvimento, Ajustes e Manutenção de sistemas legados de Recuperação de Informação, desenvolvido utilizando tecnologias como C#, Azure e Banco de Dados SQL.
    - work2:
      company: Life Developers
      location: Olinda-PE, Brasil
      title: Web Developer
      started: 2014
      duration: (2014 - 2014)
      description: Desenvolvedor Web, o trabalho consiste no desenvolvimento de websites, gerenciadores de conteúdo, criação de templates para o wordpress. Nos projetos são utilizadas as tecnologias HTML5, CSS3, JavaScrip, Framework Bootstrap, PHP e banco de dados MySQL.
    - work3:
      company: FUNESO - Fundação de Ensino Superior de Olinda
      location: Olinda-PE, Brasil
      title: Chefe Divisão de Sistema da Informação
      started: 2013
      duration: (2013 - 2014)
      description: O trabalho consiste em desenvolver um sistema web para a avaliação institucional da instituição de ensino superior FUNESO. Foi desenvolvido utilizando as tecnologias HTML5, CSS3, JavaScript, Framework Bootstrap, PHP e banco de dados MySQL. O sistema emite relatórios de resultado com gráficos utilizando a biblioteca php FPDF e PHPLOT para apresentação de gráficos.
  educationHistory:
    - education1:
      organization: Faculdade Joaquim Nabuco - FASE
      location: Olinda-PE, Brasil
      degree: Bacharel
      major: Sistema da Informação
      started: 2012.2
      duration: (2012.2 - 2016.2)
      description: 
  languages:
    - language1:
      name: English
      proficiency: Limitado
  programmingSkills:
    - skill1:
      name: HTML
      percentage: 95%
    - skill2:
      name: Bootstrap
      percentage: 90%
    - skill3:
      name: JavaScript
      percentage: 80%
    - skill4:
      name: AngularJS
      percentage: 60%
    - skill5:
      name: Java/Java EE
      percentage: 70%
    - skill6:
      name: C#
      percentage: 85%
